/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as CitiesCityIdRouteImport } from './routes/cities.$cityId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdRoute = CitiesCityIdRouteImport.update({
  id: '/cities/$cityId',
  path: '/cities/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/components': typeof ComponentsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/components': typeof ComponentsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/friends': typeof FriendsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/cities/$cityId': typeof CitiesCityIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/components/': typeof ComponentsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/discover'
    | '/friends'
    | '/itinerary'
    | '/map'
    | '/profile'
    | '/cities/$cityId'
    | '/messages/$conversationId'
    | '/settings/profile'
    | '/trips/$tripId'
    | '/components'
    | '/messages'
    | '/settings'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/discover'
    | '/friends'
    | '/itinerary'
    | '/map'
    | '/profile'
    | '/cities/$cityId'
    | '/messages/$conversationId'
    | '/settings/profile'
    | '/trips/$tripId'
    | '/components'
    | '/messages'
    | '/settings'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/discover'
    | '/friends'
    | '/itinerary'
    | '/map'
    | '/profile'
    | '/cities/$cityId'
    | '/messages/$conversationId'
    | '/settings/profile'
    | '/trips/$tripId'
    | '/components/'
    | '/messages/'
    | '/settings/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DiscoverRoute: typeof DiscoverRoute
  FriendsRoute: typeof FriendsRoute
  ItineraryRoute: typeof ItineraryRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  CitiesCityIdRoute: typeof CitiesCityIdRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId': {
      id: '/cities/$cityId'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId'
      preLoaderRoute: typeof CitiesCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DiscoverRoute: DiscoverRoute,
  FriendsRoute: FriendsRoute,
  ItineraryRoute: ItineraryRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  CitiesCityIdRoute: CitiesCityIdRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
